{
 "title": "WoodKraft Performance Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "HTTP Request Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "http_request_size_bytes" }
   ]
  },
  {
   "title": "HTTP Request Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_request_duration_microseconds"
    }
   ]
  },
  {
   "title": "HTTP Response Size",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "http_response_size_bytes" }
   ]
  },
  {
   "title": "Processes - Open file handles",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "process_open_fds" }
   ]
  }
 ]
}