module "karbon_cluster" {
  source = "./karbon_cluster"

  prism_central_username  = var.prism_central_username
  prism_central_password  = var.prism_central_password
  prism_central_endpoint  = var.prism_central_endpoint
  prism_element_cluster   = var.prism_element_cluster
  prism_element_container = var.prism_element_container
  prism_element_subnet    = var.prism_element_subnet
  insecure                = var.insecure
  prism_central_port      = var.prism_central_port
  wait_timeout            = var.wait_timeout
  karbon_cluster_name     = var.karbon_cluster_name
  kubernetes_version      = var.kubernetes_version
  pv_reclaim_policy       = var.pv_reclaim_policy
  cni_config              = var.cni_config
  worker_node_pool        = var.worker_node_pool
  etcd_node_pool          = var.etcd_node_pool
  master_node_pool        = var.master_node_pool
  active_passive_config   = var.active_passive_config
}

module "karbon_kube_config" {
  source = "./karbon_kube_config"

  prism_central_username = var.prism_central_username
  prism_central_password = var.prism_central_password
  prism_central_endpoint = var.prism_central_endpoint
  insecure               = var.insecure
  prism_central_port     = var.prism_central_port
  wait_timeout           = var.wait_timeout
  # Set dependency on karbon_cluster
  karbon_cluster_name = module.karbon_cluster.cluster_name
  kubeconfig_filename = var.kubeconfig_filename
}

module "helm_chart" {
  source = "./helm_chart"

  # Helm depends on kube.config file generated by karbon_kube_config
  kubeconfig_filename = module.karbon_kube_config.kubeconfig_filename

  helm_release = var.helm_release
}
