# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xi-iot.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='xi-iot.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0cxi-iot.proto\"4\n\x17\x44\x61taSourceFieldSelector\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"3\n\x0f\x44\x61taSourceError\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontext\x18\x02 \x01(\t\"\x9b\x01\n\x12\x44\x61taStreamMetaData\x12\r\n\x05topic\x18\x01 \x01(\t\x12,\n\ncategories\x18\x02 \x03(\x0b\x32\x18.DataSourceFieldSelector\x12\x1d\n\ttopicType\x18\x03 \x01(\x0e\x32\n.TopicType\x12\x14\n\x0cifcTopicType\x18\x04 \x01(\t\x12\x13\n\x0bifcArtifact\x18\x05 \x01(\t\"\x85\x01\n\x11\x44\x61taStreamMessage\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12%\n\x08metaData\x18\x02 \x01(\x0b\x32\x13.DataStreamMetaData\x12\x0f\n\x07payload\x18\x03 \x01(\x0c\x12%\n\x0bsourceError\x18\x04 \x01(\x0b\x32\x10.DataSourceError*L\n\tTopicType\x12\x08\n\x04MQTT\x10\x00\x12\x08\n\x04NATS\x10\x01\x12\x08\n\x04RTSP\x10\x02\x12\x0e\n\nGIGEVISION\x10\x03\x12\x11\n\rDATAINTERFACE\x10\x04\x62\x06proto3')
)

_TOPICTYPE = _descriptor.EnumDescriptor(
  name='TopicType',
  full_name='TopicType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MQTT', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NATS', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RTSP', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GIGEVISION', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DATAINTERFACE', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=417,
  serialized_end=493,
)
_sym_db.RegisterEnumDescriptor(_TOPICTYPE)

TopicType = enum_type_wrapper.EnumTypeWrapper(_TOPICTYPE)
MQTT = 0
NATS = 1
RTSP = 2
GIGEVISION = 3
DATAINTERFACE = 4



_DATASOURCEFIELDSELECTOR = _descriptor.Descriptor(
  name='DataSourceFieldSelector',
  full_name='DataSourceFieldSelector',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='DataSourceFieldSelector.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='DataSourceFieldSelector.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=68,
)


_DATASOURCEERROR = _descriptor.Descriptor(
  name='DataSourceError',
  full_name='DataSourceError',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='DataSourceError.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='context', full_name='DataSourceError.context', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=121,
)


_DATASTREAMMETADATA = _descriptor.Descriptor(
  name='DataStreamMetaData',
  full_name='DataStreamMetaData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='topic', full_name='DataStreamMetaData.topic', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='categories', full_name='DataStreamMetaData.categories', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='topicType', full_name='DataStreamMetaData.topicType', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ifcTopicType', full_name='DataStreamMetaData.ifcTopicType', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ifcArtifact', full_name='DataStreamMetaData.ifcArtifact', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=279,
)


_DATASTREAMMESSAGE = _descriptor.Descriptor(
  name='DataStreamMessage',
  full_name='DataStreamMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='DataStreamMessage.timestamp', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='metaData', full_name='DataStreamMessage.metaData', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payload', full_name='DataStreamMessage.payload', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sourceError', full_name='DataStreamMessage.sourceError', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=282,
  serialized_end=415,
)

_DATASTREAMMETADATA.fields_by_name['categories'].message_type = _DATASOURCEFIELDSELECTOR
_DATASTREAMMETADATA.fields_by_name['topicType'].enum_type = _TOPICTYPE
_DATASTREAMMESSAGE.fields_by_name['metaData'].message_type = _DATASTREAMMETADATA
_DATASTREAMMESSAGE.fields_by_name['sourceError'].message_type = _DATASOURCEERROR
DESCRIPTOR.message_types_by_name['DataSourceFieldSelector'] = _DATASOURCEFIELDSELECTOR
DESCRIPTOR.message_types_by_name['DataSourceError'] = _DATASOURCEERROR
DESCRIPTOR.message_types_by_name['DataStreamMetaData'] = _DATASTREAMMETADATA
DESCRIPTOR.message_types_by_name['DataStreamMessage'] = _DATASTREAMMESSAGE
DESCRIPTOR.enum_types_by_name['TopicType'] = _TOPICTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DataSourceFieldSelector = _reflection.GeneratedProtocolMessageType('DataSourceFieldSelector', (_message.Message,), dict(
  DESCRIPTOR = _DATASOURCEFIELDSELECTOR,
  __module__ = 'xi_iot_pb2'
  # @@protoc_insertion_point(class_scope:DataSourceFieldSelector)
  ))
_sym_db.RegisterMessage(DataSourceFieldSelector)

DataSourceError = _reflection.GeneratedProtocolMessageType('DataSourceError', (_message.Message,), dict(
  DESCRIPTOR = _DATASOURCEERROR,
  __module__ = 'xi_iot_pb2'
  # @@protoc_insertion_point(class_scope:DataSourceError)
  ))
_sym_db.RegisterMessage(DataSourceError)

DataStreamMetaData = _reflection.GeneratedProtocolMessageType('DataStreamMetaData', (_message.Message,), dict(
  DESCRIPTOR = _DATASTREAMMETADATA,
  __module__ = 'xi_iot_pb2'
  # @@protoc_insertion_point(class_scope:DataStreamMetaData)
  ))
_sym_db.RegisterMessage(DataStreamMetaData)

DataStreamMessage = _reflection.GeneratedProtocolMessageType('DataStreamMessage', (_message.Message,), dict(
  DESCRIPTOR = _DATASTREAMMESSAGE,
  __module__ = 'xi_iot_pb2'
  # @@protoc_insertion_point(class_scope:DataStreamMessage)
  ))
_sym_db.RegisterMessage(DataStreamMessage)


# @@protoc_insertion_point(module_scope)
