kind: Deployment
apiVersion: apps/v1
metadata:
  name: mqtt-sensor-app
  labels:
    app: mqtt-sensor-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt-sensor-app
  template:
    metadata:
      labels:
        app: mqtt-sensor-app
    spec:
      containers:
      - name: app-container
        image: xiiot/mqtt-sensor:0.1.0
        imagePullPolicy: Always
        command: ["/usr/local/bin/python", "/code/main.py"]
        env:
        - name: MOCK_DATA_CSV_URL
          value: "<publicly available http(s) link to data CSV>"
        - name: MQTT_INTERVAL_SEC
          value: "5"
        - name: MQTT_BROKER_IP
          value: mqttserver-svc.default
        - name: MQTT_BROKER_PORT
          value: "1883"
        - name: MQTT_TOPIC
          value: "<topic to publish on>"
        - name: MQTT_CLIENT_CERTIFICATES
          value: <base64 encoded certificate bundle>