apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secret
  labels:
    app: wordpress
type: Opaque
data:
  mysql-password: "d29yZHByZXNz"
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
      targetPort: http
  selector:
    app: wordpress
  type: ClusterIP
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: xiiot/ecomm-wordpress:v4
        env:
        - name: WORDPRESS_DB_HOST
          value: mysql
        - name: WORDPRESS_DB_USER
          value: wordpress
        - name: WORDPRESS_DB_NAME
          value: wordpress_db
        - name: WP_HOST
          value: "https://woodkraft.ntnxdomain.com"
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress-secret
              key: mysql-password
        ports:
        - containerPort: 80
          name: http
        livenessProbe:
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 6
          httpGet:
            path: /wp-login.php
            port: http
        readinessProbe:
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 6
          httpGet:
            path: /wp-login.php
            port: http
        resources:
          limits: {}
          requests:
            cpu: 300m
            memory: 512Mi

---
# Source: wordpress/templates/ingress.yaml

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: wordpress
  labels:
    app.kubernetes.io/name: wordpress
    app: wordpress
spec:
  tls:
  - hosts:
      - woodkraft.ntnxdomain.com
  rules:
    - host: woodkraft.ntnxdomain.com
      http:
        paths:
          - path: /
            backend:
              serviceName: wordpress
              servicePort: http
