prism_central_username       = "<username>"
prism_central_password       = "<password>"
prism_central_endpoint       = "<prism ip>"
prism_element_cluster        = "<ahv cluster>"
prism_element_container_name = "<storage container>"
prism_element_subnet         = "<subnet>"
karbon_cluster_name          = "<karbon cluster>"